In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [2]:
df=pd.read_csv("emails.csv")

In [3]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [4]:
df.tail()

text  spam
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

In [5]:
df.shape

(5728, 2)

In [6]:
df.dtypes

text    object
spam     int64
dtype: object

In [7]:
df.columns

Index(['text', 'spam'], dtype='object')

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.shape

(5695, 2)

In [10]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [11]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kumar\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [12]:
def process_text(text):
# remove punctuation
# remove stopwords
# return a list of clean text words
    
    #remove punctuation 
    nopunc=[char for char in text if char not in string.punctuation]
    nopunc=''.join(nopunc)
    
    #remove stopwords
    clean_words=[word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    #return a list of clean text words
    return clean_words

In [21]:
df['text'].head().apply(process_text)
# show tokenization(a list of tokens known as lemmas)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [19]:
message1='how are you  developer are you joining'
message2=' hii deni hii how are you'
# demo
print(message1)
print()
# convert text -> matrix of tokens counts
from sklearn.feature_extraction.text import CountVectorizer
bud=CountVectorizer(analyzer=process_text).fit_transform([[message1],[message2]])
print(bud)
print(bud.shape)


how are you  developer are you joining

  (0, 1)	1
  (0, 3)	1
  (1, 2)	2
  (1, 0)	1
(2, 4)


In [20]:
from sklearn.feature_extraction.text import CountVectorizer
messages_val=CountVectorizer(analyzer=process_text).fit_transform(df['text'])

# convert collection of text -> a matrix of tokens

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(messages_val,df['spam'], test_size=0.20, random_state=0)

# split data in 80% and 20% of training and testing

In [29]:
messages_val.shape

(5695, 37229)

In [31]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB().fit(X_train, y_train)
# creating and training through naive bayes classifier

In [37]:
print(classifier.predict(X_train))
# Getting the prediction or print

print(y_train.values)
# print(y_train)

# Getting the actual value or print


[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [45]:
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
pred=classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print('Confusion Matrix:\n',confusion_matrix(y_train, pred))
print()
print('Accuracy: ', accuracy_score(y_train, pred))
# evaluation of the model on the given training data set 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix:
 [[3445   12]
 [   1 1098]]

Accuracy:  0.9971466198419666


In [46]:
print(classifier.predict(X_test))
# Getting the prediction or print

print(y_test.values)
# Getting the actual value or print


[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [47]:
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
pred=classifier.predict(X_test)
print(classification_report(y_test, pred))
print()
print('Confusion Matrix:\n',confusion_matrix(y_test, pred))
print()
print('Accuracy: ', accuracy_score(y_test, pred))

# Test Data Set

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix:
 [[862   8]
 [  1 268]]

Accuracy:  0.9920983318700615
